/** Build a standalone Python downloader the user runs locally. */

export function buildPythonDownloader(posts) {
  const postsLiteral = JSON.stringify(
    posts.map((p) => ({
      date: p.date,
      link: p.link,
      variant: p.variant,
    })),
    null,
    2
  );

  return `#!/usr/bin/env python3
# Generated by TikTok Export Downloader — run on your computer:
#   python3 download_my_tiktok_videos.py
# Optional (macOS SSL): pip install certifi

from __future__ import annotations

import ssl
import sys
import time
import urllib.error
import urllib.request
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime
from pathlib import Path

POSTS = ${postsLiteral}

OUTPUT_DIR = Path("downloaded_videos")
JOBS = 4


def format_post_date_label(date_str: str) -> str:
    cleaned = date_str.removesuffix(" UTC").strip()
    posted = datetime.strptime(cleaned, "%Y-%m-%d %H:%M:%S")
    return posted.strftime("%Y-%m-%d at %H-%M-%S")


def filename_for(entry: dict) -> str:
    label = f"TikTok video - {format_post_date_label(entry['date'])}"
    if entry.get("variant", 1) > 1:
        label += f" ({entry['variant']})"
    return f"{label}.mp4"


def ssl_context() -> ssl.SSLContext:
    try:
        import certifi
        return ssl.create_default_context(cafile=certifi.where())
    except ImportError:
        return ssl.create_default_context()


def download_one(entry: dict, context: ssl.SSLContext) -> tuple[str, str]:
    dest = OUTPUT_DIR / filename_for(entry)
    if dest.exists() and dest.stat().st_size > 0:
        return filename_for(entry), "skipped"
    temp = dest.with_suffix(dest.suffix + ".part")
    last_error = "unknown error"
    for attempt in range(3):
        try:
            req = urllib.request.Request(
                entry["link"],
                headers={"User-Agent": "Mozilla/5.0 (compatible; TikTokExportDownloader/1.0)"},
            )
            with urllib.request.urlopen(req, timeout=120, context=context) as resp:
                with temp.open("wb") as out:
                    while chunk := resp.read(1024 * 256):
                        out.write(chunk)
            temp.replace(dest)
            return filename_for(entry), "ok"
        except urllib.error.HTTPError as exc:
            last_error = f"HTTP {exc.code}"
            if exc.code in (403, 404, 410):
                break
        except Exception as exc:
            last_error = str(exc)
        time.sleep(min(2 ** attempt, 10))
    if temp.exists():
        temp.unlink()
    return filename_for(entry), last_error


def main() -> int:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    ctx = ssl_context()
    print(f"Downloading {len(POSTS)} video(s) to {OUTPUT_DIR.resolve()}")
    ok = skipped = failed = 0
    failures = []
    with ThreadPoolExecutor(max_workers=JOBS) as pool:
        futures = [pool.submit(download_one, e, ctx) for e in POSTS]
        for i, fut in enumerate(as_completed(futures), 1):
            name, status = fut.result()
            if status == "ok":
                ok += 1
            elif status == "skipped":
                skipped += 1
            else:
                failed += 1
                failures.append((name, status))
            print(f"[{i}/{len(POSTS)}] {status}: {name}")
    print(f"Done: {ok} downloaded, {skipped} skipped, {failed} failed.")
    if failures:
        (OUTPUT_DIR / "download_failures.txt").write_text(
            "\\n".join(f"{n}\\t{e}" for n, e in failures) + "\\n",
            encoding="utf-8",
        )
        if any("403" in e for _, e in failures):
            print("Many 403 errors mean CDN links expired. Request a fresh TikTok data export.")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
`;
}
